name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-11-jdk \
          zip \
          unzip \
          git \
          wget \
          curl \
          libncurses5 \
          python3-pip \
          autoconf \
          automake \
          libtool \
          pkg-config
        
    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.19
        
    - name: Setup Android SDK and NDK manually
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        # Download Android SDK
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip -q commandlinetools-linux-8512546_latest.zip
        mv cmdline-tools android-sdk
        
        # Download Android NDK
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        mv android-ndk-r25b android-ndk
        
    - name: Clone python-for-android manually
      run: |
        cd ~/.buildozer/android/platform
        git clone https://github.com/kivy/python-for-android.git
        cd python-for-android
        pip install -e .
        
    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: laila-chatbot-apk
        path: bin/*.apk
        retention-days: 7
