name: Build APK Manual Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK
      run: |
        buildozer android update
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: laila-chatbot-apk
        path: bin/*.apk
