name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-8-jdk zip unzip libncurses5
        pip install buildozer
        
    - name: Build APK
      run: |
        buildozer android debug
        ls -la bin/
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: laila-chatbot-apk
        path: bin/*.apk
        retention-days: 7
