name: Build APK Manual Setup

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-11-jdk \
          zip \
          unzip \
          git \
          wget \
          curl \
          libncurses5 \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.19 kivy
        
    - name: Manual python-for-android setup
      run: |
        # Create necessary directories
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        # Clone python-for-android
        git clone https://github.com/kivy/python-for-android.git
        cd python-for-android
        pip install -e .
        
        # Setup Android SDK and NDK
        python -m pythonforandroid.toolchain create --help
        
    - name: Build using direct p4a
      run: |
        # Use python-for-android directly
        cd ~/.buildozer/android/platform/python-for-android
        python -m pythonforandroid.toolchain create \
          --dist_name=laila_chatbot \
          --bootstrap=sdl2 \
          --requirements=python3,kivy \
          --arch=arm64-v8a \
          --arch=armeabi-v7a \
          --copy-libs \
          --color=always \
          --storage-dir=$GITHUB_WORKSPACE/.buildozer/android/platform/build \
          --ndk-api=21 \
          --ignore-setup-py \
          --debug
          
    - name: Package APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer -v android debug
          
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: laila-chatbot-apk
        path: bin/*.apk
        retention-days: 7
