name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Buildozer Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-11-jdk \
          zip \
          unzip \
          git \
          wget
        
    - name: Install Buildozer
      run: pip install buildozer
        
    - name: Initialize Buildozer (if no spec file)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
    - name: Build APK (Single Arch - Faster)
      run: |
        buildozer android clean
        buildozer -v android debug 2>&1 | tail -50
        
    - name: Check for APK
      run: |
        find . -name "*.apk" | head -5
        ls -la bin/ || echo "No bin directory"
        
    - name: Upload APK if exists
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: laila-chatbot-apk
        path: |
          bin/*.apk
          *.apk
        retention-days: 5 
